version: "3.3"
services:
  generate:
    build:
      context: .
      dockerfile:  Generate.Dockerfile
    environment:
      API_RESOURCE_DIRECTORY: /home/generate/api-resources
      GENERATED_KOTLIN_TARGET_DIRECTORY: /home/generate/generated/kotlin
    volumes:
      - "./api-resources/:/home/generate/api-resources/:rw"
      - "./generated/src/main/:/home/generate/generated/:rw"
    network_mode: host