version: "3.3"
services:
  web:
    ports: 
      - "80:80" 
    build:
      context: .
      dockerfile:  Web.Dockerfile
    network_mode: host
  api:
    build:
      context: .
      dockerfile: Api.Dockerfile
    network_mode: host
    environment:
      API_RESOURCE_DIRECTORY: /home/api/api-resources
    volumes:
      - "./api-resources/:/home/api/api-resources/:rw"