version: "3.3"
services:
  web:
    build:
      context: .
      dockerfile:  Web.Dockerfile
    environment:
      API_RESOURCE_DIRECTORY: /home/web/api-resources
      API_RESOURCE_CONFIG_DIRECTORY: /home/web/config
    volumes:
      - "./api-resources/:/home/web/api-resources/:rw"
      - "./web/src/main/resources/config/:/home/web/config/:rw"
    network_mode: host
  api:
    build:
      context: .
      dockerfile: Api.Dockerfile
    network_mode: host
    environment:
      API_RESOURCE_DIRECTORY: /home/api/api-resources
    volumes:
      - "./api-resources/:/home/api/api-resources/:rw"